apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      #securityContext:
      #  fsGroup: 33 # www-data group ID
      #  runAsUser: 33 # www-data user ID
      #  runAsGroup: 33 # www-data group ID

      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v3.0.2
          ports:
            - containerPort: 9000

          #envFrom:
          #  - secretRef:
          #      name: mealie-container-env

          #securityContext:
          #  allowPrivilegeEscalation: false

          volumeMounts:
            - name: mealie-data
              mountPath: /etc/mealie/data
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data-pvc
