apiVersion: apps/v1
kind: Deployment
metadata:
  name: mealie
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mealie
  template:
    metadata:
      labels:
        app: mealie
    spec:
      securityContext:
        fsGroup: 911 # abc group ID
        runAsUser: 911 # abc user ID
        runAsGroup: 911 # abc group ID

      containers:
        - name: mealie
          image: ghcr.io/mealie-recipes/mealie:v3.3.1
          ports:
            - containerPort: 9000

          #envFrom:
          #  - secretRef:
          #      name: mealie-container-env

          securityContext:
            allowPrivilegeEscalation: false

          volumeMounts:
            - name: mealie-data
              mountPath: /app/data
      volumes:
        - name: mealie-data
          persistentVolumeClaim:
            claimName: mealie-data-pvc
