apiVersion: v1
data:
    credentials.json: ENC[AES256_GCM,data:EyJK1XNvOvgelOydWT57GVKAjmx4BHp3AmD8sGg4o3KJYey6yn8VHf+UrMkgpm+6+zUzYVZWVcEcsFP/MxUDqqWKrPny81u4LUxUBcLWZnbA4GV2YnIPYWqOFPMAMyJHsNMTXhQBHew+7Gg2z3SmMv+SJD7noXurqWkdP3OxEbH6Zhr4TG5kuHmLnA76wsoyMKAKyEF3VVqJl1uU6Q+TadLrb7iU76TxfcRPL4NlgLG/mXJ+Tlwdqjtqc7Uo4BsVFCgj6wKe34zMjEqmRb/ISk6sYDXMwFzo9jNByoD1g44whK5ofE0bKqspLDg=,iv:hxzaNOMbDtOF7EUzp+NBkPOwHrsn0a80EglEbpSZmB0=,tag:tWMoA08s4lzuvX9C0uhO1w==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: tunnel-credentials-audiobookshelf
sops:
    age:
        - recipient: age1500f0hmp383fj0pj2j573fftts4nuy8uumshxucyvjf2sz5fkejsd6xyz3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBWdlFDZVhhYlVZcEgrS2J5
            bHFucDdKY1dtTDZidlk3UzVTMFdJeE5aUWxvCmtsdTlIQitVdC9iZERaSDhvSUJk
            MStxYVNvM3BOaGJadDQ4Z3BEajU5RncKLS0tIHJmUXgxMHcyaW5KTVVoNE01aXpk
            cWVpU2lkU0Nqc0hUcjlkcmpyZ3JMTDQKB3XQ6xfpGO0YuCI1WbigeMMIhoxPk0YA
            3xzcez/d3yasQ6mSrBhTfIzri/IYvI4dpqK1/CEeuwXeRSOgrylxzg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-31T23:29:18Z"
    mac: ENC[AES256_GCM,data:hRwp4ili7WjIcect8ywe1lENBVhduOje/3/QfzGtnJyN8C9ZFUtL5b0CmCJQmuiPUHuSGo1dF0yuCq9eedzMwyHoHuia1GTFKl80m4M9kNJjJeXqeV87UQX3ZkoSRx6XW22va00WUs61HPlMX/dFa5MAFNu4NmRmFB8PBlbL184=,iv:IuZolWTG3+ogLtjMqQrN3pr5Q3AE6LETkbnn07qS7SA=,tag:3vtrQ+OnffbrD8zliXlI7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2