apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: audiobookshelf
resources:
  - ../../base/audiobookshelf/
  - cftunnel-audiobookshelf.yaml
  - cfsecret-audiobookshelf.yaml
  - audiobookshelf-container-env-secret.yaml
  - ingress.yaml