apiVersion: v1
data:
    TZ: ENC[AES256_GCM,data:f8atpZLweoQPeJLF14IkBb6LO7o=,iv:UyALmVt/a9qjwpu9ePW5WgA9/FRxSe6cu5MDUVzDyJw=,tag:aNmu0MZOc3dmSd6VGWk6Fg==,type:str]
    WEBPASSWORD: ENC[AES256_GCM,data:ASgaJtlWS3I=,iv:TocwoVJhigEQsPPuPxMqoDlMr/JcBKJVa1cWJavEu5M=,tag:yKtPwMuXqZ1mJt8D45AT7A==,type:str]
kind: Secret
metadata:
    creationTimestamp: null
    name: pihole-container-env
sops:
    age:
        - recipient: age1500f0hmp383fj0pj2j573fftts4nuy8uumshxucyvjf2sz5fkejsd6xyz3
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnQnF6ZWl6K1pzei9reWNw
            MmhOdmI0RE1kWExtb0xLTUxOVWl0T29RYkY4CmhsZnNnZ0J2UlVmSmxrNGJHUXhw
            RkdRL3I0eW5KYjgrSU5IVFoyRzQ2YzgKLS0tIGoySnBZcW82NzJ0MVVWTnRCbnlt
            T0tyQWtOOXFRRlZySTV2K2swS1RKMXcKQEcLN+H75Is3NuCYP+x1u+Ihhbnnvvzl
            msaZvw1kAVwn0SWH3dtXnJhu0J2sRkq9Rkr/YsDHv29IcF0gd66/bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-07-31T03:05:57Z"
    mac: ENC[AES256_GCM,data:w7c6ZU5Sl3FrZ+QFemU18Y726NqtrXKkyklPL5YvaGdskRWDJUybwruGwEqS9tJn6aUDkw9sPQv/8GwhoSbcY013IUIAr1A9DFd54RpvglF7cHY9VgGPPR3WTNE/xfICgtd6l/r52TnOoSgqCI0ZSjnVd+ceNXlsbu9RuHaEmHM=,iv:iPVD5b0/xVaJ3NS0fmAu683JnegLw0wH5aUuHJ5BU60=,tag:e2NJ6AzMttOCuWp26hmODg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2