apiVersion: v1
kind: Service
metadata:
  name: pihole-service-dns
  namespace: pihole
  labels:
    app: pihole
spec:
  selector:
    app: pihole
  type: NodePort
  ports:
    - name: dns-udp
      protocol: UDP
      port: 53
    - name: dns-tcp
      protocol: TCP
      port: 53
  externalIPs:
    - 192.168.42.211
