apiVersion: v1
kind: Service
metadata:
  name: pihole-service-web
  namespace: pihole
  labels:
    app: pihole
spec:
  selector:
    app: pihole
  type: NodePort
  ports:
    - name: web
      protocol: TCP
      port: 80
