apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-pv
  namespace: pihole
  labels:
    app: pihole
spec:
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/pihole-data" # Adjust this path on your node
